### ISSUE TITLE
bee missing

### ISSUE THREAD

**Issue by sdubois** [lando/backdrop#36]
The bee command line tool is missing from the backdrop recipe plugin.

According to the lando documentation, this should be included by default. https://docs.lando.dev/backdrop/tooling.html

I can even see script in the plugin that looks like it should install bee (https://github.com/lando/backdrop/blob/7610f6fd9f212608caa37aa7e23967007a524f90/scripts/install-bee.sh). But myself and someone else in the Backdrop Zulip chat can confirm that on lando (v) it is missing. You can see the conversation here: https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Bee.20in.20lando

**Comment by sdubois** [comment]
That should say lando v3.20.8, which is the latest version as of today

**Comment by reynoldsalec** [comment]
Bee should be deployed in the latest version(s) of the Backdrop recipe; upgrade to Lando v3.21 and make sure you have the latest Backdrop recipe by running `lando update`
